// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbpJ0niM_9xzmOC_oaqharjT1ZRbjzah0',
    appId: '1:278594467225:web:bb77c48d6cec961e3dcf08',
    messagingSenderId: '278594467225',
    projectId: 'debatematef',
    authDomain: 'debatematef.firebaseapp.com',
    storageBucket: 'debatematef.firebasestorage.app',
    measurementId: 'G-0652K89KQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbpJ0niM_9xzmOC_oaqharjT1ZRbjzah0',
    appId: '1:278594467225:android:bb77c48d6cec961e3dcf08',
    messagingSenderId: '278594467225',
    projectId: 'debatematef',
    storageBucket: 'debatematef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:123456789012:ios:abcdef1234567890abcdef12',
    messagingSenderId: '123456789012',
    projectId: 'debate-mate-app',
    storageBucket: 'debate-mate-app.appspot.com',
    iosBundleId: 'com.example.debateMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:123456789012:ios:abcdef1234567890abcdef12',
    messagingSenderId: '123456789012',
    projectId: 'debate-mate-app',
    storageBucket: 'debate-mate-app.appspot.com',
    iosBundleId: 'com.example.debateMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:123456789012:web:abcdef1234567890abcdef12',
    messagingSenderId: '123456789012',
    projectId: 'debate-mate-app',
    authDomain: 'debate-mate-app.firebaseapp.com',
    storageBucket: 'debate-mate-app.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );
}